services:
  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app1
      - app2
  app1:
    image: efkumah/docker-nginx-app # pull image from docker hub
    container_name: app1_container
    healthcheck:
      test: ["CMD", "wget", "-q0-", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
  app2:
    image: efkumah/docker-nginx-app # pull image from docker hub
    container_name: app2_container
    healthcheck:
      test: ["CMD", "wget", "-q0-", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
